spring:
  application:
    name: spring-boot-teacher-subject
  datasource:
    url: jdbc:postgresql://localhost:5432/restDB
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
